/******************************************************************************
 * Copyright (c) 2026, Lucas Kirschner <kirschnerlucas1@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 *****************************************************************************/

/**
 * @file    app_user.c
 * @author  Lucas Kirschner <kirschnerlucas1@gmail.com>
 * @date    2026-05-27
 * @brief   User application task implementation.
 *
 * @details
 * This module provides the user application entry point.
 *
 * The file is intentionally organized with USER CODE sections, following a
 * style similar to the one generated by STM32CubeMX. These sections indicate
 * where the final user can add application-specific code without modifying the
 * base firmware layers.
 *
 * This implementation provides a minimal radio reception test intended for a
 * node configured as IEEE 802.15.4 PAN coordinator.
 *
 * The coordinator does not actively transmit application data. It periodically
 * checks the radio RX queue and prints every received one-byte message together
 * with the source node short address.
 *
 * IEEE 802.15.4 acknowledgment generation is handled automatically by the
 * MRF24J40 hardware and therefore requires no application-level processing in
 * this task.
 *
 * @note
 * The number of retransmissions performed by a remote transmitter cannot be
 * determined by the coordinator from the received application frame. Retry
 * information belongs to the transmitting MRF24J40 and is available locally
 * through its TX result.
 *
 * @ingroup app_user
 * @{
 */

/* Includes ------------------------------------------------------------------*/
#include "cmsis_os2.h"

#include <stdint.h>
#include <stdio.h>

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

#include "app_user.h"
#include "app_radio.h"
#include "app_din.h"
#include "app_dout.h"
#include "app_rs485.h"

#include "swo.h"

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/**
 * @brief Period, in milliseconds, between user application updates.
 *
 * @details
 * A short polling period is used because app_radio_receive() is non-blocking.
 */
#define APP_USER_UPDATE_PERIOD_MS   ((uint32_t)10u)

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
 * @brief User application task.
 *
 * @param argument Task argument. Not used.
 *
 * @details
 * This task implements a minimal PAN coordinator reception test.
 *
 * Code inside USER CODE BEGIN app_init is executed once before the periodic
 * loop starts.
 *
 * Code inside USER CODE BEGIN app_task periodically checks the radio input
 * queue. Each received message contains:
 *
 * - source IEEE 802.15.4 short address
 * - one-byte application payload
 *
 * The radio application and MRF24J40 driver are responsible for MAC frame
 * processing and automatic acknowledgment generation.
 */
void app_user_task(void * argument)
{
    (void)argument;

    /* USER CODE BEGIN app_init */

    printf("\r\n");
    printf("[APP_USER] Radio PAN coordinator test\r\n");
    printf("[APP_USER] Waiting for remote device frames...\r\n");

    /* USER CODE END app_init */

    for (;;)
    {
        /* USER CODE BEGIN app_task */

        uint16_t source;
        uint8_t data;
        app_radio_status_t radio_status;

        /*
         * Drain every message currently available in the RX queue.
         *
         * app_radio_receive() is non-blocking, so APP_RADIO_E_QUEUE_EMPTY
         * terminates the loop immediately when there is no more pending data.
         */
        do
        {
            radio_status = app_radio_receive(&source, &data);

            if (radio_status == APP_RADIO_OK)
            {
                printf("[APP_USER] RX src=0x%04X data=0x%02X (%u)\r\n",
                       source,
                       data,
                       data);
            }
            else if (radio_status == APP_RADIO_E_QUEUE_EMPTY)
            {
                /* No more received messages are currently pending. */
            }
            else
            {
                printf("[APP_USER] RX error=%d\r\n",
                       (int)radio_status);
            }

        } while (radio_status == APP_RADIO_OK);

        /* USER CODE END app_task */

        osDelay(APP_USER_UPDATE_PERIOD_MS);
    }
}

/* USER CODE BEGIN 1 */

/* USER CODE END 1 */

/** @} */
