/******************************************************************************
 * Copyright (c) 2026, Lucas Kirschner <kirschnerlucas1@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 ******************************************************************************/

/**
 * @file    rs485_port.c
 * @author  Lucas Kirschner <kirschnerlucas1@gmail.com>
 * @date    2026-08-08
 * @brief   BSP port layer implementation for the RS485 interface.
 *
 * @details
 * This module wraps STM32 HAL UART and GPIO services for a half-duplex RS485
 * interface connected to UART7.
 *
 * Both transmission and reception use interrupt-driven UART services:
 *
 * - HAL_UART_Transmit_IT().
 * - HAL_UART_Receive_IT().
 *
 * Consequently, the calling firmware is not blocked while the UART peripheral
 * performs the communication.
 *
 * Transfer completion and communication errors are detected through the STM32
 * HAL callbacks:
 *
 * - HAL_UART_TxCpltCallback(): Requested transmission completed.
 * - HAL_UART_RxCpltCallback(): Requested reception completed.
 * - HAL_UART_ErrorCallback(): UART communication error detected.
 *
 * These HAL callbacks are implemented in this module and filtered so that only
 * events associated with UART7 are processed.
 *
 * The callbacks update the internal port state and propagate the asynchronous
 * events to the upper RS485 driver through weak notification hooks:
 *
 * - rs485_port_tx_complete_callback().
 * - rs485_port_rx_complete_callback().
 * - rs485_port_error_callback().
 *
 * The upper RS485 driver may provide strong definitions of these functions.
 * Their implementations must remain short and ISR-safe because they execute
 * from UART interrupt context.
 *
 * The port layer controls the external RS485 transceiver through the DE and
 * /RE GPIO signals, but it does not define the half-duplex communication
 * policy. Mode transitions between transmission and reception are requested by
 * the upper RS485 driver through rs485_port_set_mode().
 *
 * The default idle state is receive mode:
 *
 * - DE = 0: RS485 line driver disabled.
 * - /RE = 0: RS485 receiver enabled.
 *
 * This module does not use DMA, dynamic memory or RTOS services.
 *
 * @ingroup rs485_port
 * @{
 */

/* ============================= Includes ================================== */

#include "rs485_port.h"

#include "main.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* ============================ Local Types ================================ */

/**
 * @brief Internal RS485 port context.
 */
typedef struct
{
    /**
     * @brief Indicates whether the port layer has been initialized.
     */
    bool initialized;

    /**
     * @brief Indicates that an interrupt-driven reception is active.
     */
    volatile bool rx_active;

    /**
     * @brief Indicates that an interrupt-driven transmission is active.
     */
    volatile bool tx_active;

    /**
     * @brief Last UART error flags reported by the STM32 HAL.
     */
    volatile uint32_t last_uart_error;

} rs485_port_ctx_t;

/* ======================= Local Static Data ================================ */

/**
 * @brief Internal RS485 port context.
 */
static rs485_port_ctx_t g_ctx = {
    .initialized = false,
    .rx_active = false,
    .tx_active = false,
    .last_uart_error = HAL_UART_ERROR_NONE
};

/* ======================= External Peripheral Data ======================== */

/**
 * @brief UART handle generated by STM32CubeMX for the RS485 interface.
 */
extern UART_HandleTypeDef huart7;

/* ===================== Private Function Prototypes ======================= */

static rs485_port_status_t rs485_port_validate_handle(
    const rs485_port_handle_t * handle);

static rs485_port_status_t rs485_port_hal_to_status(
    HAL_StatusTypeDef hal_status);

/* ===================== Public Function Definitions ======================= */

rs485_port_status_t rs485_port_init(
    rs485_port_handle_t * handle)
{
    rs485_port_status_t status;

    status = rs485_port_validate_handle(handle);

    if (status != RS485_PORT_OK)
    {
        return status;
    }

    if (g_ctx.initialized != false)
    {
        return RS485_PORT_E_STATE;
    }

    /*
     * Place the external transceiver in its default idle state before
     * enabling the port context.
     */
    status = rs485_port_set_mode(
        RS485_PORT_MODE_RX);

    if (status != RS485_PORT_OK)
    {
        return status;
    }

    g_ctx.rx_active = false;
    g_ctx.tx_active = false;
    g_ctx.last_uart_error = HAL_UART_ERROR_NONE;

    g_ctx.initialized = true;

    return RS485_PORT_OK;
}

rs485_port_status_t rs485_port_deinit(
    rs485_port_handle_t * handle)
{
    rs485_port_status_t status;

    status = rs485_port_validate_handle(handle);

    if (status != RS485_PORT_OK)
    {
        return status;
    }

    if (g_ctx.initialized == false)
    {
        return RS485_PORT_E_STATE;
    }

    /*
     * Abort any pending UART operations.
     *
     * The return values are intentionally ignored because one or both UART
     * directions may already be idle.
     */
    (void)HAL_UART_AbortReceive(&huart7);
    (void)HAL_UART_AbortTransmit(&huart7);

    g_ctx.rx_active = false;
    g_ctx.tx_active = false;
    g_ctx.last_uart_error = HAL_UART_ERROR_NONE;

    /*
     * Restore the external transceiver to its safe idle state.
     */
    status = rs485_port_set_mode(
        RS485_PORT_MODE_RX);

    if (status != RS485_PORT_OK)
    {
        return status;
    }

    g_ctx.initialized = false;

    return RS485_PORT_OK;
}

rs485_port_status_t rs485_port_set_mode(
    rs485_port_mode_t mode)
{
    switch (mode)
    {
        case RS485_PORT_MODE_RX:

            /*
             * Disable the line driver before enabling the receiver.
             *
             * DE  = 0
             * /RE = 0
             */
            HAL_GPIO_WritePin(
                RS485_DE_GPIO_Port,
                RS485_DE_Pin,
                GPIO_PIN_RESET);

            HAL_GPIO_WritePin(
                RS485_RE_GPIO_Port,
                RS485_RE_Pin,
                GPIO_PIN_RESET);

            break;

        case RS485_PORT_MODE_TX:

            /*
             * Disable the receiver before enabling the line driver.
             *
             * DE  = 1
             * /RE = 1
             *
             * Disabling the receiver prevents locally transmitted data from
             * being received by the same UART.
             */
            HAL_GPIO_WritePin(
                RS485_RE_GPIO_Port,
                RS485_RE_Pin,
                GPIO_PIN_SET);

            HAL_GPIO_WritePin(
                RS485_DE_GPIO_Port,
                RS485_DE_Pin,
                GPIO_PIN_SET);

            break;

        default:

            return RS485_PORT_E_PARAM;
    }

    return RS485_PORT_OK;
}

rs485_port_status_t rs485_port_transmit_it(
    uint8_t * data,
    uint16_t size)
{
    HAL_StatusTypeDef hal_status;

    if (data == NULL)
    {
        return RS485_PORT_E_NULL;
    }

    if (size == 0u)
    {
        return RS485_PORT_E_PARAM;
    }

    if (g_ctx.initialized == false)
    {
        return RS485_PORT_E_STATE;
    }

    /*
     * The current half-duplex implementation allows only one UART operation
     * at a time.
     */
    if ((g_ctx.tx_active != false) ||
        (g_ctx.rx_active != false))
    {
        return RS485_PORT_E_STATE;
    }

    g_ctx.last_uart_error = HAL_UART_ERROR_NONE;

    hal_status = HAL_UART_Transmit_IT(
        &huart7,
        data,
        size);

    if (hal_status == HAL_OK)
    {
        g_ctx.tx_active = true;
    }

    return rs485_port_hal_to_status(
        hal_status);
}

rs485_port_status_t rs485_port_receive_it(
    uint8_t * data,
    uint16_t size)
{
    HAL_StatusTypeDef hal_status;

    if (data == NULL)
    {
        return RS485_PORT_E_NULL;
    }

    if (size == 0u)
    {
        return RS485_PORT_E_PARAM;
    }

    if (g_ctx.initialized == false)
    {
        return RS485_PORT_E_STATE;
    }

    /*
     * The current half-duplex implementation allows only one UART operation
     * at a time.
     */
    if ((g_ctx.rx_active != false) ||
        (g_ctx.tx_active != false))
    {
        return RS485_PORT_E_STATE;
    }

    g_ctx.last_uart_error = HAL_UART_ERROR_NONE;

    hal_status = HAL_UART_Receive_IT(
        &huart7,
        data,
        size);

    if (hal_status == HAL_OK)
    {
        g_ctx.rx_active = true;
    }

    return rs485_port_hal_to_status(
        hal_status);
}

rs485_port_status_t rs485_port_abort_transmit(void)
{
    HAL_StatusTypeDef hal_status;

    if (g_ctx.initialized == false)
    {
        return RS485_PORT_E_STATE;
    }

    /*
     * If no transmission is active, the requested final state has already
     * been reached.
     */
    if (g_ctx.tx_active == false)
    {
        return RS485_PORT_OK;
    }

    hal_status = HAL_UART_AbortTransmit(
        &huart7);

    if (hal_status == HAL_OK)
    {
        g_ctx.tx_active = false;
        g_ctx.last_uart_error = HAL_UART_ERROR_NONE;
    }

    return rs485_port_hal_to_status(
        hal_status);
}

rs485_port_status_t rs485_port_abort_receive(void)
{
    HAL_StatusTypeDef hal_status;

    if (g_ctx.initialized == false)
    {
        return RS485_PORT_E_STATE;
    }

    /*
     * If no reception is active, the requested final state has already been
     * reached.
     */
    if (g_ctx.rx_active == false)
    {
        return RS485_PORT_OK;
    }

    hal_status = HAL_UART_AbortReceive(
        &huart7);

    if (hal_status == HAL_OK)
    {
        g_ctx.rx_active = false;
        g_ctx.last_uart_error = HAL_UART_ERROR_NONE;
    }

    return rs485_port_hal_to_status(
        hal_status);
}

/* ===================== HAL Callback Definitions ========================== */

/**
 * @brief STM32 HAL UART transmission-complete callback.
 *
 * @param[in,out] huart  UART handle associated with the completed
 *                      transmission.
 *
 * @details
 * HAL calls this function after HAL_UART_Transmit_IT() has transmitted the
 * requested number of bytes.
 *
 * Only UART7 events are processed. The callback clears the local active
 * transmission state and invokes rs485_port_tx_complete_callback().
 *
 * The RS485 transceiver operating mode is intentionally not modified here.
 * The upper RS485 driver is responsible for deciding the half-duplex state
 * transition after transmission completion.
 *
 * This function executes in interrupt context and must remain short.
 */
void HAL_UART_TxCpltCallback(
    UART_HandleTypeDef * huart)
{
    if (huart == &huart7)
    {
        g_ctx.tx_active = false;
        g_ctx.last_uart_error = HAL_UART_ERROR_NONE;

        rs485_port_tx_complete_callback();
    }
}

/**
 * @brief STM32 HAL UART reception-complete callback.
 *
 * @param[in,out] huart  UART handle associated with the completed reception.
 *
 * @details
 * HAL calls this function after HAL_UART_Receive_IT() has received the
 * requested number of bytes.
 *
 * Only UART7 events are processed. The callback clears the local active
 * reception state and invokes rs485_port_rx_complete_callback().
 *
 * This function executes in interrupt context and must remain short.
 */
void HAL_UART_RxCpltCallback(
    UART_HandleTypeDef * huart)
{
    if (huart == &huart7)
    {
        g_ctx.rx_active = false;
        g_ctx.last_uart_error = HAL_UART_ERROR_NONE;

        rs485_port_rx_complete_callback();
    }
}

/**
 * @brief STM32 HAL UART error callback.
 *
 * @param[in,out] huart  UART handle associated with the detected error.
 *
 * @details
 * Only UART7 errors are processed.
 *
 * The callback stores the UART error flags, clears both active-transfer state
 * indicators and invokes rs485_port_error_callback().
 *
 * Possible HAL error flags include:
 *
 * - HAL_UART_ERROR_PE: Parity error.
 * - HAL_UART_ERROR_NE: Noise error.
 * - HAL_UART_ERROR_FE: Framing error.
 * - HAL_UART_ERROR_ORE: Overrun error.
 *
 * The external RS485 transceiver operating mode is intentionally not modified
 * here. Recovery policy is delegated to the upper RS485 driver.
 *
 * This function executes in interrupt context and must remain short.
 */
void HAL_UART_ErrorCallback(
    UART_HandleTypeDef * huart)
{
    uint32_t error_code;

    if (huart == &huart7)
    {
        error_code = HAL_UART_GetError(
            huart);

        g_ctx.last_uart_error = error_code;

        g_ctx.rx_active = false;
        g_ctx.tx_active = false;

        rs485_port_error_callback(
            error_code);
    }
}

/* ================= Notification Hook Definitions ========================= */

/**
 * @brief Default transmission-complete notification hook.
 *
 * @details
 * This weak implementation intentionally performs no operation.
 *
 * The upper RS485 driver may provide a strong definition to process the
 * asynchronous transmission-complete notification.
 */
__weak void rs485_port_tx_complete_callback(void)
{
    /* Upper-layer notification hook. */
}

/**
 * @brief Default reception-complete notification hook.
 *
 * @details
 * This weak implementation intentionally performs no operation.
 *
 * The upper RS485 driver may provide a strong definition to process the
 * asynchronous reception-complete notification.
 */
__weak void rs485_port_rx_complete_callback(void)
{
    /* Upper-layer notification hook. */
}

/**
 * @brief Default UART-error notification hook.
 *
 * @param[in] error_code  UART error flags.
 *
 * @details
 * This weak implementation intentionally performs no operation.
 *
 * The upper RS485 driver may provide a strong definition to process the
 * asynchronous UART-error notification.
 */
__weak void rs485_port_error_callback(
    uint32_t error_code)
{
    (void)error_code;
}

/* ===================== Private Function Definitions ====================== */

/**
 * @brief Validate the public RS485 port handle.
 *
 * @param[in] handle  RS485 port handle.
 *
 * @return RS485_PORT_OK on success.
 * @return RS485_PORT_E_NULL if handle is NULL.
 */
static rs485_port_status_t rs485_port_validate_handle(
    const rs485_port_handle_t * handle)
{
    if (handle == NULL)
    {
        return RS485_PORT_E_NULL;
    }

    return RS485_PORT_OK;
}

/**
 * @brief Convert STM32 HAL status codes to RS485 port status codes.
 *
 * @param[in] hal_status  Status returned by an STM32 HAL function.
 *
 * @return Equivalent RS485 port status code.
 */
static rs485_port_status_t rs485_port_hal_to_status(
    HAL_StatusTypeDef hal_status)
{
    rs485_port_status_t status;

    switch (hal_status)
    {
        case HAL_OK:

            status = RS485_PORT_OK;
            break;

        case HAL_TIMEOUT:

            status = RS485_PORT_E_TIMEOUT;
            break;

        case HAL_BUSY:

            status = RS485_PORT_E_STATE;
            break;

        case HAL_ERROR:
        default:

            status = RS485_PORT_E_HW;
            break;
    }

    return status;
}

/** @} */
