/******************************************************************************
 * Copyright (c) 2026, Lucas Kirschner <kirschnerlucas1@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 ******************************************************************************/

/**
 * @file    app_rs485.h
 * @author  Lucas Kirschner <kirschnerlucas1@gmail.com>
 * @date    2026-08-08
 * @brief   RS485 application service interface.
 *
 * @details
 * This module provides the application-level interface for asynchronous
 * single-byte RS485 communication.
 *
 * The module owns the underlying RS485 driver and serializes access to the
 * half-duplex communication interface through app_rs485_task().
 *
 * Communication with the rest of the firmware is performed through RTOS
 * message queues:
 *
 * - app_rs485_send() places one byte into the transmission queue.
 * - app_rs485_receive() retrieves one byte from the reception queue.
 *
 * Both public functions are non-blocking.
 *
 * The internal RS485 task performs all driver operations and handles the
 * asynchronous notifications generated by the lower RS485 driver.
 *
 * Reception flow:
 *
 * @code
 * RS485 UART RX interrupt
 *          |
 *          v
 * rs485_rx_complete_callback()
 *          |
 *          v
 * APP_RS485_EVT_RX_READY
 *          |
 *          v
 * app_rs485_task()
 *          |
 *          v
 * rs485_receive()
 *          |
 *          v
 * rs485InputQueueHandle
 *          |
 *          v
 * app_rs485_receive()
 * @endcode
 *
 * Transmission flow:
 *
 * @code
 * app_rs485_send()
 *          |
 *          v
 * rs485OutputQueueHandle
 *          |
 *          v
 * APP_RS485_EVT_TX_REQUEST
 *          |
 *          v
 * app_rs485_task()
 *          |
 *          v
 * rs485_send()
 *          |
 *          v
 * RS485 UART TX interrupt
 *          |
 *          v
 * rs485_tx_complete_callback()
 * @endcode
 *
 * This module does not implement any application-specific behavior such as
 * echo, command interpretation, framing or protocol processing.
 *
 * Such functionality belongs to upper application tasks, for example
 * app_user_task().
 *
 * @defgroup app_rs485 RS485 Application Service
 * @{
 */

#ifndef APP_RS485_H_
#define APP_RS485_H_

/* ============================= Includes ================================== */

#include <stdint.h>

/* ============================ Public Macros =============================== */

/**
 * @brief RS485 reception-complete event.
 */
#define APP_RS485_EVT_RX_READY             ((uint32_t)(1u << 0))

/**
 * @brief RS485 transmission request event.
 */
#define APP_RS485_EVT_TX_REQUEST           ((uint32_t)(1u << 1))

/**
 * @brief RS485 transmission-complete event.
 */
#define APP_RS485_EVT_TX_COMPLETE          ((uint32_t)(1u << 2))

/**
 * @brief RS485 communication-error event.
 */
#define APP_RS485_EVT_ERROR                ((uint32_t)(1u << 3))

/**
 * @brief Mask containing all RS485 application events.
 */
#define APP_RS485_EVT_MASK                 \
    (APP_RS485_EVT_RX_READY      |         \
     APP_RS485_EVT_TX_REQUEST    |         \
     APP_RS485_EVT_TX_COMPLETE   |         \
     APP_RS485_EVT_ERROR)

/* ------------------------------------------------------------------------ */

/**
 * @brief RS485 driver initialization fault.
 */
#define APP_RS485_FAULT_INIT_ERROR         ((uint32_t)(1u << 0))

/**
 * @brief Invalid null pointer fault.
 */
#define APP_RS485_FAULT_NULL_ERROR         ((uint32_t)(1u << 1))

/**
 * @brief Invalid parameter fault.
 */
#define APP_RS485_FAULT_PARAM_ERROR        ((uint32_t)(1u << 2))

/**
 * @brief Invalid driver state fault.
 */
#define APP_RS485_FAULT_STATE_ERROR        ((uint32_t)(1u << 3))

/**
 * @brief Communication timeout fault.
 */
#define APP_RS485_FAULT_TIMEOUT            ((uint32_t)(1u << 4))

/**
 * @brief RS485 hardware communication fault.
 */
#define APP_RS485_FAULT_HW_ERROR           ((uint32_t)(1u << 5))

/**
 * @brief RS485 receive queue full fault.
 */
#define APP_RS485_FAULT_RX_QUEUE_FULL      ((uint32_t)(1u << 6))

/**
 * @brief RS485 transmit queue full fault.
 */
#define APP_RS485_FAULT_TX_QUEUE_FULL      ((uint32_t)(1u << 7))

/**
 * @brief RTOS service fault.
 */
#define APP_RS485_FAULT_OS_ERROR           ((uint32_t)(1u << 8))

/**
 * @brief Mask containing all RS485 fault flags.
 */
#define APP_RS485_FAULT_ERROR_MASK         (APP_RS485_FAULT_INIT_ERROR       | \
                                            APP_RS485_FAULT_NULL_ERROR       | \
                                            APP_RS485_FAULT_PARAM_ERROR      | \
                                            APP_RS485_FAULT_STATE_ERROR      | \
                                            APP_RS485_FAULT_TIMEOUT          | \
                                            APP_RS485_FAULT_HW_ERROR         | \
                                            APP_RS485_FAULT_RX_QUEUE_FULL    | \
                                            APP_RS485_FAULT_TX_QUEUE_FULL    | \
                                            APP_RS485_FAULT_OS_ERROR)

/* ============================ Public Types ================================ */

/**
 * @brief RS485 application service status.
 */
typedef enum
{
    APP_RS485_OK = 0,

    APP_RS485_E_NULL,
    APP_RS485_E_STATE,
    APP_RS485_E_QUEUE_FULL,
    APP_RS485_E_QUEUE_EMPTY,
    APP_RS485_E_OS

} app_rs485_status_t;

/* ===================== Public Function Prototypes ========================= */

/**
 * @brief RS485 application service task.
 *
 * @param[in] argument  Optional RTOS task argument.
 *
 * @details
 * This task is the exclusive owner of the underlying RS485 driver.
 *
 * It initializes the driver, keeps interrupt-driven reception armed while the
 * interface is idle, processes completed receptions, services pending
 * transmission requests and handles asynchronous communication errors.
 *
 * The task normally remains blocked on an RTOS event flag while no RS485
 * activity is pending.
 *
 * This function is intended to be used as a CMSIS-RTOS2 thread entry point and
 * does not return.
 */
void app_rs485_task(
    void * argument);

/**
 * @brief Queue one byte for asynchronous RS485 transmission.
 *
 * @param[in] data  Byte to be transmitted.
 *
 * @return APP_RS485_OK if the byte was queued successfully.
 * @return APP_RS485_E_STATE if the RS485 service is not initialized.
 * @return APP_RS485_E_QUEUE_FULL if the transmission queue is full.
 * @return APP_RS485_E_OS if an RTOS operation fails.
 *
 * @details
 * This function is non-blocking.
 *
 * The byte is placed into the RS485 transmission queue and the RS485 task is
 * notified through APP_RS485_EVT_TX_REQUEST.
 *
 * A successful return indicates that the transmission request was accepted by
 * the application service. It does not indicate that the byte has already been
 * physically transmitted.
 */
app_rs485_status_t app_rs485_send(
    uint8_t data);

/**
 * @brief Retrieve one received RS485 byte.
 *
 * @param[out] p_data  Pointer where the received byte will be stored.
 *
 * @return APP_RS485_OK if one byte was retrieved successfully.
 * @return APP_RS485_E_NULL if p_data is NULL.
 * @return APP_RS485_E_STATE if the RS485 service is not initialized.
 * @return APP_RS485_E_QUEUE_EMPTY if no received byte is available.
 * @return APP_RS485_E_OS if an RTOS operation fails.
 *
 * @details
 * This function is non-blocking.
 *
 * Received bytes are placed into the input queue by app_rs485_task() after the
 * lower RS485 driver reports reception completion.
 */
app_rs485_status_t app_rs485_receive(
    uint8_t * p_data);

/** @} */

#endif /* APP_RS485_H_ */
