/******************************************************************************
 * Copyright (c) 2026, Lucas Kirschner <kirschnerlucas1@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 ******************************************************************************/

/**
 * @file    app_user.c
 * @author  Lucas Kirschner <kirschnerlucas1@gmail.com>
 * @date    2026-05-27
 * @brief   User application task implementation.
 *
 * @details
 * This module provides the user application entry point.
 *
 * The file is intentionally organized with USER CODE sections, following a
 * style similar to the one generated by STM32CubeMX. These sections indicate
 * where the final user can add application-specific code without modifying the
 * base firmware layers.
 *
 * The user application task provides two main editable regions:
 *
 * - app_init: code executed once before entering the task loop.
 * - app_task: code executed periodically every
 *   APP_USER_OUTPUT_UPDATE_PERIOD_MS milliseconds.
 *
 * The default template does not implement process logic. The final user should
 * place the required application-specific behavior inside the provided USER
 * CODE sections.
 *
 * @ingroup app_user
 * @{
 */

/* Includes ------------------------------------------------------------------*/
#include "cmsis_os2.h"

#include <stdint.h>
#include <stdio.h>

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

#include "app_user.h"
#include "app_radio.h"
#include "app_din.h"
#include "app_dout.h"

#include "swo.h"

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/**
 * @brief Period, in milliseconds, between user application updates.
 */
#define APP_USER_UPDATE_PERIOD_MS   ((uint32_t)1000u)

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
 * @brief User application task.
 *
 * @param argument Task argument. Not used.
 *
 * @details
 * This task is the main user application execution context.
 *
 * Code inside USER CODE BEGIN app_init is executed once before the periodic
 * loop starts.
 *
 * Code inside USER CODE BEGIN app_task is executed periodically. The execution
 * period is defined by APP_USER_OUTPUT_UPDATE_PERIOD_MS.
 */
void app_user_task(void * argument)
{
    (void)argument;

    /* USER CODE BEGIN app_init */

    /* USER CODE END app_init */

    for (;;)
    {
        /* USER CODE BEGIN app_task */

        /* USER CODE END app_task */

        osDelay(APP_USER_UPDATE_PERIOD_MS);
    }
}

/* USER CODE BEGIN 1 */

/* USER CODE END 1 */

/** @} */
